import Head from "next/head";
import styles from "../styles/Layout.module.scss";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";
import { useEffect, useState } from "react";
import { logout } from "../store/actions/authActions";
import { useRouter } from "next/router";

const Layout = ({ children }) => {
  const dispatch = useDispatch();
  const authState = useSelector((state) => state.auth);
  const [render, setRender] = useState(false);
  const router = useRouter();

  useEffect(() => {
    setRender(true);
    if (!authState.authenticated) {
      router.replace("/login");
    }
  }, [authState]);
  return (
    <>
      <Head>
        <title>BallDon&apos;tLie Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {render ? (
        <nav className={styles.navBar}>
          <div className="container">
            <a href="#" className={styles.brand}>
              BallDon&apos;tLie
            </a>
            <span>
              <Link href="/players">
                <a>Players</a>
              </Link>
              <Link href="/teams">
                <a>Teams</a>
              </Link>
            </span>
            <span>
              <a>{authState?.user?.name}</a>
              <a href="#" onClick={() => dispatch(logout())}>
                Logout
              </a>
            </span>
          </div>
        </nav>
      ) : (
        <></>
      )}

      <main className={styles.mainContent}>{children}</main>
    </>
  );
};

export default Layout;
